ProyectoEstandares3/ProyectoEstandares3/Models/HojaEgreso.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaEgreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HojaEgreso()
        {
            this.DetalleEgreso = new HashSet<DetalleEgreso>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Suma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEgreso> DetalleEgreso { get; set; }
    }
}

ProyectoEstandares3/ProyectoEstandares3/Controllers/HojaEgresoController.cs
using ProyectoEstandares3.Datos;
using ProyectoEstandares3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEstandares3.Controllers
{
    public class HojaEgresoController : Controller
    {
        //Un objeto del tipo de entidad, no lo he borrado por si acaso.
        FerreSoriano17Entities db = new FerreSoriano17Entities();

        //Objetos de las clases de la capa de datos
        HojaEgresoAdmin hoja = new HojaEgresoAdmin();
        DetalleEgresoAdmin detHoja = new DetalleEgresoAdmin();
        InventarioAdmin inven = new InventarioAdmin();
        AlmacenesAdmin alll = new AlmacenesAdmin();
        AlmacenInventarioAdmin alma = new AlmacenInventarioAdmin();
        KardexAdmin kar = new KardexAdmin();

        // GET: HojaEgreso

        //Index para mostrar la tabla de datos "HojaEgreso"
        public ActionResult Index(String mensaje = "")
        {
            ViewBag.confirmacion = mensaje;
            IEnumerable<HojaEgreso> lista = hoja.Consultar();
            return View(lista);
        }

        //public ActionResult ObtenerUltimoID(HojaEgreso modelo) {
        //    return RedirectToAction("Guardar", new { id = modelo.Id });
        //}


        //Método que abre la vista "Guardar", con un formulario para guardar los
        //de la compra.
        public ActionResult Guardar()
        {
            //HojaEgreso modelo = new HojaEgreso() { 
            //    Documento = "DOC-" + (id+1)
            //};
            return View();
        }

        //Al enviar los datos de la compra nueva, se guardan en la tabla de la BD
        //Y se llama a la vista "RegistrosEgreso", la cual muestra los datos de 
        //HojaEgresoDetalle ligados a la compra recíen ingresada por el usuario
        //Por ello se envia un argumento del ID de la compra ingresada.
        public ActionResult NuevoEgreso(HojaEgreso modelo)
        {
            string laFecha = "" + modelo.Fecha;
            if (!laFecha.Equals(""))
            {
                hoja.Guardar(modelo);
                ViewBag.alerta = "";
                return RedirectToAction("RegistrosEgreso", new { id = modelo.Id, total = 0 });
            }
            else
            {
                ViewBag.alerta = "Debe ingresar una fecha";
                return View("Guardar");
            }
        }

        //Método para guardar los registros de los detalles de la compra recién ingresada
        //Esta vista muestra los datos de la compra a realizar. Y abajo muestra una tabla
        //Que permitirá al usuario ver los registros de aquellos productos que formarán
        //Parte de la compra, con sus cantidades y precio unitario. Además del almacén en donde
        //Estos productos serán guardados.

        //Aquí se usa ViewBag para poder enviar como propiedades los detalles de HojaEgreso
        //Y se envía un modelo de una colección de datos para llenar la tabla para HojaEgresoDETALLE
        public ActionResult RegistrosEgreso(int id = 0, double total = 0)
        {
            //ESTAS SÓLO FUERON PRUEBAS, ESTAS LÍNEAS NO FUNCIONAN
            //ViewBag.CompraDocumento = "DOC00001";
            //ViewBag.CompraProveedor = "Empresaxyz";
            //-------------------
            //ViewBag.CompraDocumento = comp.ConsultaDocumento(id);
            //ViewBag.CompraProveedor = comp.ConsultaProveedor(id).ToString();

            //ESTAS LÍNEAS SI FUNCIONAN PERFECTAMENTE

            //Se crea un modelo de la clase HojaEgreso que almacena los datos obtenidos por el método "ObtenerDetalles"
            HojaEgreso modelo = hoja.ObtenerDetalles(id);
            //Se almacenan algunas propiedades del modelo en variables del mismo tipo de dato
            //para luego ser almacenados en variables ViewBag
            int comID = (int)modelo.Id;
            ViewBag.EgresoID = comID;
            DateTime ComF = (DateTime)modelo.Fecha;
            String FechaNueva = ComF.Date.ToShortDateString();
            ViewBag.EgresoFecha = FechaNueva;
            ViewBag.FechaNoVisible = ComF;

            ViewBag.EgresoPrecioTotal = total;

            //Colección de datos de HojaEgresoDetalle
            IEnumerable<DetalleEgreso> lista = detHoja.ConsultaDetalles(id);
            ICollection<DetalleEgreso> listadoDetalles = new List<DetalleEgreso>();
            using (var sequenceEnum = lista.GetEnumerator())
            {
                while (sequenceEnum.MoveNext())
                {
                    DetalleEgreso modelo1 = sequenceEnum.Current;
                    Inventario inv = inven.ConsultaDetalle(modelo1.Id_inventario);
                    string nombreInv = inv.Descripcion;
                    Almacenes alm = alll.ConsultaDetalle(modelo1.Id_almacen);
                    string nombreAl = alm.Nombre;
                    DetalleEgreso modeloNuevo = new DetalleEgreso()
                    {
                        Id_detalle = modelo1.Id_detalle,
                        Id_hojaEgreso = modelo1.Id_hojaEgreso,
                        Id_almacen = modelo1.Id_almacen,
                        Almacen = nombreAl,
                        Id_inventario = modelo1.Id_inventario,
                        Inventario2 = nombreInv,
                        Cantidad = modelo1.Cantidad,
                        Precio = modelo1.Precio,
                        PrecioTotal = modelo1.PrecioTotal
                    };
                    listadoDetalles.Add(modeloNuevo);
                }
            }
            return View(listadoDetalles);
        }

        //Método que permite agregar el registro de un producto con su cantidad, precio y almacén a una compra específica.
        public ActionResult AgregarRegistrosEgreso(int id = 0, int idinventario = 0, int idalmacen = 0, int cantid = 0, int? prec = 0, double total = 0, string mensaje = "")
        {
            DetalleEgreso modelo = new DetalleEgreso()
            {
                Id_hojaEgreso = id,
                Id_inventario = idinventario,
                Id_almacen = idalmacen,
                Cantidad = cantid,
                Precio = prec
            };
            ViewBag.EgresoPrecioTotal = total;
            ViewBag.alerta = mensaje;
            //HojaEgreso modelo = comp.ObtenerDetalles(id);
            //int comID = (int)modelo.Id;
            //ViewBag.CompraID = comID;
            return View(modelo);
        }

        //Este método se ejecuta cuando se manda el formulario de la vista "AgregarRegistrosEgreso", se guarda
        //el nuevo registro en la tabla "HojaEgresoDetalle" y se redirecciona a la vista "RegistrosEgreso"
        //porque en ese instante todavía se sigue rellenando los detalles del egreso.
        public ActionResult NuevoRegistrosEgreso(DetalleEgreso modelo, double total = 0)
        {
            //Se obtienen los detalles del formulario
            string laCantidad = "" + modelo.Cantidad;
            int? CantidadDefecto = 0 + modelo.Cantidad;
            string elPrecio = "" + modelo.Precio;
            decimal? PrecioDefecto = 0 + modelo.Precio;
            int IdInv = modelo.Id_inventario;
            int IdAl = modelo.Id_almacen;
            double todoElPrecio;

            //Se chequea si los campos no están vacíos
            if (!laCantidad.Equals("") && !elPrecio.Equals(""))
            {
                //Se chequea si los campos no contienen cero
                if (CantidadDefecto != 0 && PrecioDefecto != 0)
                {
                    Inventario modeloInv = inven.ConsultaDetalle(IdInv);
                    int stockMini = modeloInv.StockMinimo;
                    int Existencias = modeloInv.Existencia;
                    int nuevaExis = (int)modelo.Cantidad;
                    int posibleExis = Existencias - nuevaExis;

                    Almacen_Inventario modeloAlma = alma.ConsultaEspecifica(IdAl, IdInv);
                    int? cantAlmacen = modeloAlma.Existencia;

                    int? nuevaCantAlmacen = cantAlmacen - nuevaExis;

                    int Disponible = Existencias - stockMini;

                    if (cantAlmacen >= nuevaExis)
                    {
                        if (posibleExis >= stockMini)
                        {
                            double Cant2 = (double)modelo.Cantidad;
                            double Prec2 = (double)modelo.Precio;
                            double PrecioT2 = Cant2 * Prec2;
                            DetalleEgreso modelo3 = new DetalleEgreso()
                            {
                                Id_hojaEgreso = modelo.Id_hojaEgreso,
                                Id_inventario = modelo.Id_inventario,
                                Id_almacen = modelo.Id_almacen,
                                Cantidad = modelo.Cantidad,
                                Precio = modelo.Precio,
                                PrecioTotal = (decimal?)PrecioT2
                            };
                            //Se guarda el registro en la tabla DetalleEgreso
                            detHoja.Guardar(modelo3);

                            //Aquí actualizaremos los datos del registro de la tabla Inventario en donde el ID_inventario sea igual al que se ha registrado en este detalle del egreso
                            var resultado = (from p in db.Inventario
                                             where p.Id == IdInv
                                             select p).SingleOrDefault();
                            resultado.Existencia = posibleExis;
                            db.SaveChanges();


                            //Aquí actualizaremos los datos del registro de la tabla Almacen_Inventario
                            var resultado2 = (from p in db.Almacen_Inventario
                                              where p.Id_almacen == IdAl && p.Id_inventario == IdInv
                                              select p).SingleOrDefault();

ProyectoEstandares3/ProyectoEstandares3/Views/HojaEgreso/AgregarRegistrosEgreso.cshtml
@model ProyectoEstandares3.Models.DetalleEgreso

@{
    ViewBag.Title = "Agregar nuevo registro de egreso";
}

<h2>Agregar nuevo registro de egreso</h2>


@using (Html.BeginForm("NuevoRegistrosEgreso", "HojaEgreso", new { ReturnUrl = ViewBag.ReturnUrl , total = ViewBag.EgresoPrecioTotal }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @{
        if (!string.IsNullOrEmpty(ViewBag.alerta))
        {
            // Message tiene un valor
            <div class="alert alert-danger">@ViewBag.alerta</div>
        }
    }
    <dl class="dl-horizontal">
        <dt>
            Total del egreso:
        </dt>

        <dd>
            @ViewBag.EgresoPrecioTotal
        </dd>
    </dl>

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id_hojaEgreso, "Id_hojaEgreso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_hojaEgreso, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Id_hojaEgreso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_inventario, "Id_inventario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_inventario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id_inventario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_almacen, "Id_almacen", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_almacen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id_almacen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar en egreso" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar a egreso", "RegistrosEgreso", new { id = Model.Id_hojaEgreso , total = ViewBag.EgresoPrecioTotal})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEstandares3/ProyectoEstandares3/Views/HojaEgreso/Guardar.cshtml
@model ProyectoEstandares3.Models.HojaEgreso

@{
    ViewBag.Title = "Registrar egreso";
}

<h2>Registrar egreso</h2>


@using (Html.BeginForm("NuevoEgreso", "HojaEgreso", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @{
        if (!string.IsNullOrEmpty(ViewBag.alerta))
        {
            // Message tiene un valor
            <div class="alert alert-danger">@ViewBag.alerta</div>
        }
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @Value = @String.Format("{0:yyyy/MM/dd}", DateTime.Now) } })
            @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Siguiente" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEstandares3/ProyectoEstandares3/Views/HojaEgreso/Index.cshtml
@model IEnumerable<ProyectoEstandares3.Models.HojaEgreso>

@{
    ViewBag.Title = "Hojas de egreso";
}

<h2>Hojas de egreso</h2>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <font color="green">@ViewBag.confirmacion</font>
    </div>
</div>
<br />
<p>
    @Html.ActionLink("Registrar nuevo egreso", "Guardar")
</p>
<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suma)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @(String.Format("{0:yyyy/MM/dd}", item.Fecha))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Suma)
            </td>
            <td>
                @Html.ActionLink("Detalles", "TodoElEgreso", new { id = item.Id })
            </td>
        </tr>
    }

</table>

ProyectoEstandares3/ProyectoEstandares3/Views/HojaEgreso/RegistrosEgreso.cshtml
@model IEnumerable<ProyectoEstandares3.Models.DetalleEgreso>

@{
    ViewBag.Title = "Detalles del Egreso";
}

<h2>Detalles del Egreso</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HojaEgreso.Id)
        </dt>

        <dd>
            @ViewBag.EgresoID
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HojaEgreso.Fecha)
        </dt>

        <dd>
            @ViewBag.EgresoFecha
        </dd>

    </dl>
</div>


<hr>
<br>
@Html.ActionLink("Agregar nuevo registro para el egreso", "AgregarRegistrosEgreso", new { id = ViewBag.EgresoID, idinventario = 0, idalmacen = 0, cantid = 0, prec = 0, total = ViewBag.EgresoPrecioTotal, mensaje = "" })
<br>
<table class="table" style="background-color:white">
    <tr>
        <th>
            Inventario
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Almacen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Almacen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioTotal)
            </td>
            <td>
                @Html.ActionLink("Borrar", "Eliminar", new { id = item.Id_detalle, id_doc = ViewBag.EgresoID, todoElPrecio = ViewBag.EgresoPrecioTotal })
            </td>
        </tr>
    }
</table>

<div>
    <dl class="dl-horizontal">
        <dt>
            Precio total del egreso:
        </dt>
        <dd>
            @ViewBag.EgresoPrecioTotal
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Finalizar egreso", "EgresoFinalizado", new { fecha = ViewBag.FechaNoVisible, id = ViewBag.EgresoID, total = ViewBag.EgresoPrecioTotal })
</div>

ProyectoEstandares3/ProyectoEstandares3/Views/HojaEgreso/TodoElEgreso.cshtml
@model IEnumerable<ProyectoEstandares3.Models.DetalleEgreso>

@{
    ViewBag.Title = "Detalles del Egreso";
}

<h2>Detalles del Egreso</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HojaEgreso.Id)
        </dt>

        <dd>
            @ViewBag.EgresoID
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HojaEgreso.Suma)
        </dt>

        <dd>
            @ViewBag.EgresoSuma
        </dd>
    </dl>
</div>


<hr>
<table class="table" style="background-color:white">
    <tr>
        <th>
            Inventario
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Almacen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Almacen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioTotal)
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Regresar", "Index", "HojaEgreso")
</div>