ProyectoEstandares3/ProyectoEstandares3/Models/Categorias.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorias()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}

ProyectoEstandares3/ProyectoEstandares3/Controllers/CategoriasController.cs
using ProyectoEstandares3.Datos;
using ProyectoEstandares3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEstandares3.Controllers
{
    public class CategoriasController : Controller
    {
        CategoriasAdmin usu = new CategoriasAdmin();
        // GET: Categorias
        public ActionResult Index()
        {
            IEnumerable<Categorias> lista = usu.Consultar();
            return View(lista);
        }

        public ActionResult Guardar()
        {
            ViewBag.mensaje = "";
            return View();
        }
        
        //METODO CON VALIDACIONES
        public ActionResult Nuevo(Categorias modelo)
        {
            //Se obtiene el valor del form
            string laDescripcion = modelo.Descripcion;

            //Si no está vacío
            if (laDescripcion != null)
            {
                //Se guarda la info
                usu.Guardar(modelo);
                ViewBag.mensaje = "Categoría guardada con éxito";
                ViewBag.alerta = "";
            }//Si no, muestra un mensaje de alerta
            else
            {
                ViewBag.mensaje = "";
                ViewBag.alerta = "Ingrese todos los datos";
            }
            return View("Guardar", modelo);
        }

        public ActionResult Detalle(int id = 0)
        {
            Categorias modelo = usu.ConsultaDetalle(id);
            return View(modelo);
        }

        public ActionResult Modificar(int id = 0)
        {
            Categorias modelo = usu.ConsultaDetalle(id);
            ViewBag.mensaje = "";
            return View(modelo);
        }

        //METODO CON VALIDACIONES
        //Funciona con la misma lógica que el método "Nuevo", no hace falta documentarlo
        public ActionResult Actualizar(Categorias modelo)
        {
            string laDescripcion = modelo.Descripcion;

            if (laDescripcion != null)
            {
                usu.Modificar(modelo);
                ViewBag.mensaje = "Categoria modificada con éxito";
                ViewBag.alerta = "";
            }
            else
            {
                ViewBag.mensaje = "";
                ViewBag.alerta = "Ingrese todos los datos";
            }
            return View("Modificar", modelo);
        }

        public ActionResult Eliminar(int id = 0)
        {
            Categorias modelo = new Categorias()
            {
                Id = id
            };
            usu.Eliminar(modelo);
            IEnumerable<Categorias> lista = usu.Consultar();
            ViewBag.mensaje = "Categoria eliminada con éxito";
            return View("Index", lista);
        }
    }
}

ProyectoEstandares3/ProyectoEstandares3/Views/Categorias/Detalle.cshtml
@model ProyectoEstandares3.Models.Categorias

@{
    ViewBag.Title = "Detalle de la categoría";
}

<h2>Detalle de la categoría</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Modificar", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoEstandares3/ProyectoEstandares3/Views/Categorias/Guardar.cshtml
@model ProyectoEstandares3.Models.Categorias

@{
    ViewBag.Title = "Guardar categoría";
}

<h2>Guardar categoría</h2>


@using (Html.BeginForm("Nuevo", "Categorias", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @{
        if (!string.IsNullOrEmpty(ViewBag.alerta))
        {
            // Message tiene un valor
            <div class="alert alert-danger">@ViewBag.alerta</div>
        }
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <font color="green">@ViewBag.mensaje</font>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEstandares3/ProyectoEstandares3/Views/Categorias/Index.cshtml
@model IEnumerable<ProyectoEstandares3.Models.Categorias>

@{
    ViewBag.Title = "Lista de categorías";
}

<h2>Lista de categorías</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Guardar")
</p>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <font color="green">@ViewBag.mensaje</font>
    </div>
</div>
<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Modificar", new { id=item.Id }) |
            @Html.ActionLink("Ver", "Detalle", new { id=item.Id }) |
            @Html.ActionLink("Borrar", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>

ProyectoEstandares3/ProyectoEstandares3/Views/Categorias/Modificar.cshtml
@model ProyectoEstandares3.Models.Categorias

@{
    ViewBag.Title = "Modificar categoría";
}

<h2>Modificar categoría</h2>


@using (Html.BeginForm("Actualizar", "Categorias", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Categorias</h4>
    <hr />
    @{
        if (!string.IsNullOrEmpty(ViewBag.alerta))
        {
            // Message tiene un valor
            <div class="alert alert-danger">@ViewBag.alerta</div>
        }
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Modificar" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <font color="green">@ViewBag.mensaje</font>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}