ProyectoEstandares3/ProyectoEstandares3/Models/Compras.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.ComprasDetalle = new HashSet<ComprasDetalle>();
        }
    
        public int Id { get; set; }
        public string Documento { get; set; }
        public Nullable<int> Id_proveedor { get; set; }
        public string Proveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Sumas { get; set; }
        public Nullable<decimal> Iva { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDetalle> ComprasDetalle { get; set; }
    }
}

ProyectoEstandares3/ProyectoEstandares3/Controllers/ComprasController.cs
using ProyectoEstandares3.Datos;
using ProyectoEstandares3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEstandares3.Controllers
{
    public class ComprasController : Controller
    {
        //Un objeto del tipo de entidad, no lo he borrado por si acaso.
        FerreSoriano17Entities db = new FerreSoriano17Entities();
        
        //Objetos de las clases de la capa de datos
        ComprasAdmin comp = new ComprasAdmin();
        ComprasDetalleAdmin detComp = new ComprasDetalleAdmin();
        InventarioAdmin inven = new InventarioAdmin();
        AlmacenesAdmin alll = new AlmacenesAdmin();
        AlmacenInventarioAdmin alma = new AlmacenInventarioAdmin();
        KardexAdmin kar = new KardexAdmin();
        ProveedoresAdmin prov = new ProveedoresAdmin();

        // GET: Compras
        
        //Index para mostrar la tabla de datos "Compras"
        public ActionResult Index(String mensaje = "")
        {
            IEnumerable<int> listaComp = comp.ConsultarIDS();
            ICollection<Compras> listadoCompras = new List<Compras>();
            string Provee = "";
            foreach (int dato in listaComp)
            {
                Compras mComp = comp.ObtenerDetalles(dato);
                Proveedores prv = prov.ConsultaDetalle((int)mComp.Id_proveedor);
                Provee = prv.Nombre;
                Compras modeloComp = new Compras()
                {
                    Id = mComp.Id,
                    Documento = mComp.Documento,
                    Proveedor = Provee,
                    Fecha = mComp.Fecha,
                    Sumas = mComp.Sumas,
                    Iva = mComp.Iva
                };
                listadoCompras.Add(modeloComp);
            }
                ViewBag.confirmacion = mensaje;
            return View(listadoCompras);
        }

        //public ActionResult ObtenerUltimoID(Compras modelo) {
        //    return RedirectToAction("Guardar", new { id = modelo.Id });
        //}


        //Método que abre la vista "Guardar", con un formulario para guardar los
        //de la compra.
        public ActionResult Guardar()
        {
            Compras modelo = comp.ObtenerUltimo();
            int ultimoID = 0;
            if (modelo != null) {
                ultimoID += modelo.Id;
            }
            ultimoID++;
            Compras modelo2 = new Compras()
            {
                Documento = "DOC-" + ultimoID
            };
            return View(modelo2);
        }

        //Al enviar los datos de la compra nueva, se guardan en la tabla de la BD
        //Y se llama a la vista "DetalleCompra", la cual muestra los datos de 
        //ComprasDetalle ligados a la compra recíen ingresada por el usuario
        //Por ello se envia un argumento del ID de la compra ingresada.
        public ActionResult NuevaCompra(Compras modelo) {
            comp.Guardar(modelo);
            return RedirectToAction("DetalleCompra", new { id = modelo.Id, total = 0 });
        }

        //Método para guardar los registros de los detalles de la compra recién ingresada
        //Esta vista muestra los datos de la compra a realizar. Y abajo muestra una tabla
        //Que permitirá al usuario ver los registros de aquellos productos que formarán
        //Parte de la compra, con sus cantidades y precio unitario. Además del almacén en donde
        //Estos productos serán guardados.

        //Aquí se usa ViewBag para poder enviar como propiedades los detalles de COMPRAS
        //Y se envía un modelo de una colección de datos para llenar la tabla para COMPRASDETALLE
        public ActionResult DetalleCompra(int id = 0, double total = 0)
        {
            //ESTAS SÓLO FUERON PRUEBAS, ESTAS LÍNEAS NO FUNCIONAN
            //ViewBag.CompraDocumento = "DOC00001";
            //ViewBag.CompraProveedor = "Empresaxyz";
            //-------------------
            //ViewBag.CompraDocumento = comp.ConsultaDocumento(id);
            //ViewBag.CompraProveedor = comp.ConsultaProveedor(id).ToString();

            //ESTAS LÍNEAS SI FUNCIONAN PERFECTAMENTE
                
            //Se crea un modelo de la clase Compras que almacena los datos obtenidos por el método "ObtenerDetalles"
            Compras modelo = comp.ObtenerDetalles(id);
            //Se almacenan algunas propiedades del modelo en variables del mismo tipo de dato
            //para luego ser almacenados en variables ViewBag
            int comID = (int)modelo.Id;
            ViewBag.CompraID = comID;
            String comD = modelo.Documento;
            ViewBag.CompraDocumento = comD;
            int comP = (int)modelo.Id_proveedor;
            Proveedores provvv = prov.ConsultaDetalle(comP);
            string nombreProv = provvv.Nombre;
            ViewBag.CompraProveedor = comP;
            ViewBag.CompraProveedorNombre = nombreProv;
            DateTime ComF = modelo.Fecha;
            String FechaNueva = ComF.Date.ToShortDateString();
            ViewBag.CompraFecha = FechaNueva;
            ViewBag.FechaNoVisible = ComF;

            ViewBag.CompraPrecioTotal = total;

            //Colección de datos de ComprasDetalle
            IEnumerable<ComprasDetalle> lista = detComp.ConsultaDetalles(id);
            ICollection<ComprasDetalle> listadoDetalles = new List<ComprasDetalle>();
            using (var sequenceEnum = lista.GetEnumerator())
            {
                while (sequenceEnum.MoveNext())
                {
                    ComprasDetalle modelo1 = sequenceEnum.Current;
                    Inventario inv = inven.ConsultaDetalle(modelo1.Id_inventario);
                    string nombreInv = inv.Descripcion;
                    Almacenes alm = alll.ConsultaDetalle(modelo1.Id_almacen);
                    string nombreAl = alm.Nombre;
                    ComprasDetalle modeloNuevo = new ComprasDetalle()
                    {
                        Id = modelo1.Id,
                        Id_documento = modelo1.Id_documento,
                        Id_almacen = modelo1.Id_almacen,
                        Almacen = nombreAl,
                        Id_inventario = modelo1.Id_inventario,
                        Inventario = nombreInv,
                        Cantidad = modelo1.Cantidad,
                        Precio = modelo1.Precio,
                        PrecioTotal = modelo1.PrecioTotal
                    };
                    listadoDetalles.Add(modeloNuevo);
                }
            }
            return View(listadoDetalles);
        }

        //Método que permite agregar el registro de un producto con su cantidad, precio y almacén a una compra específica.
        public ActionResult AgregarDetallesCompra(int id = 0, int idinventario = 0, int idalmacen = 0, int? cantid = 0, int? prec = 0, double total = 0, string mensaje = "") {
            ComprasDetalle modelo = new ComprasDetalle()
            {
                Id_documento = id,
                Id_inventario = idinventario,
                Id_almacen = idalmacen,
                Cantidad = cantid,
                Precio = prec
            };
            ViewBag.CompraPrecioTotal = total;
            ViewBag.alerta = mensaje;
            //Compras modelo = comp.ObtenerDetalles(id);
            //int comID = (int)modelo.Id;
            //ViewBag.CompraID = comID;
            return View(modelo);
        }

        //Este método se ejecuta cuando se manda el formulario de la vista "AgregarDetallesCompra", se guarda
        //el nuevo registro en la tabla "ComprasDetalle" y se redirecciona a la vista "DetalleCompra"
        //porque en ese instante todavía se sigue rellenando los detalles de la compra.

        //En el método se modifican también los registros de existencias de las tablas "Inventario" y "Almacen_inventario"

        //Y también se crea el método para mandar el registro del detalle de la compra a la tabla "Kardex"
        public ActionResult NuevoDetalleCompra(ComprasDetalle modelo, double total = 0)
        {
            //Se obtienen los detalles del formulario
            string laCantidad = "" + modelo.Cantidad;
            int? CantidadDefecto = 0 + modelo.Cantidad;
            string elPrecio = "" + modelo.Precio;
            decimal? PrecioDefecto = 0 + modelo.Precio;
            int IdInv = modelo.Id_inventario;
            int IdAl = modelo.Id_almacen;
            double todoElPrecio;

            //Se chequea si los campos no están vacíos
            if (!laCantidad.Equals("") && !elPrecio.Equals("")) 
            {
                //Se chequea si los campos no contienen cero
                if (CantidadDefecto != 0 && PrecioDefecto != 0)
                {
                    Inventario modeloInv = inven.ConsultaDetalle(IdInv);
                    int stockMaxi = modeloInv.StockMaximo;
                    int Existencias = modeloInv.Existencia;
                    int nuevaExis = (int)modelo.Cantidad;
                    int posibleExis = nuevaExis + Existencias;

                    Almacen_Inventario modeloAlma = alma.ConsultaEspecifica(IdAl, IdInv);
                    int? cantAlmacen = modeloAlma.Existencia;

                    int? nuevaCantAlmacen = cantAlmacen + nuevaExis;

                    int Disponible = stockMaxi - Existencias;

                    if (posibleExis <= stockMaxi)
                    {
                        //Aqui mandaremos el dato del detalle de la compra hacia la tabla correspondiente.
                        double Cant = (double)modelo.Cantidad;
                        double Prec = (double)modelo.Precio;
                        double PrecioT = Cant * Prec;
                        ComprasDetalle modelo2 = new ComprasDetalle()
                        {
                            Id_documento = modelo.Id_documento,
                            Id_inventario = modelo.Id_inventario,
                            Id_almacen = modelo.Id_almacen,

ProyectoEstandares3/ProyectoEstandares3/Views/Compras/AgregarDetallesCompra.cshtml
@model ProyectoEstandares3.Models.ComprasDetalle

@{
    ViewBag.Title = "Agregar registro de detalle de la compra";
}

<h2>Agregar registro de detalle de la compra</h2>


@using (Html.BeginForm("NuevoDetalleCompra", "Compras", new { ReturnUrl = ViewBag.ReturnUrl , total = ViewBag.CompraPrecioTotal }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @{
        if (!string.IsNullOrEmpty(ViewBag.alerta))
        {
            // Message tiene un valor
            <div class="alert alert-danger">@ViewBag.alerta</div>
        }
    }
    <dl class="dl-horizontal">
        <dt>
            Total de la compra:
        </dt>

        <dd>
            @ViewBag.CompraPrecioTotal
        </dd>
    </dl>

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id_documento, "Id_documento", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_documento, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Id_documento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_inventario, "Id_inventario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_inventario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id_inventario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_almacen, "Id_almacen", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_almacen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id_almacen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar en compra" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar a compra", "DetalleCompra", new { id = Model.Id_documento, total = ViewBag.CompraPrecioTotal });
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEstandares3/ProyectoEstandares3/Views/Compras/DetalleCompra.cshtml
@model IEnumerable<ProyectoEstandares3.Models.ComprasDetalle>

@{
    ViewBag.Title = "Detalles de la Compra";
}

<h2>Detalles de la compra</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Compras.Id)
        </dt>

        <dd>
            @ViewBag.CompraID
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Documento)
        </dt>

        <dd>
            @ViewBag.CompraDocumento
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Proveedor)
        </dt>

        <dd>
            @ViewBag.CompraProveedorNombre
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Fecha)
        </dt>

        <dd>
            @ViewBag.CompraFecha
        </dd>

    </dl>
</div>


<hr>
<br>
@Html.ActionLink("Agregar nuevo registro para la compra", "AgregarDetallesCompra", new { id = ViewBag.CompraID , idinventario = 0, idalmacen = 0, cantid = 0, prec = 0, total = ViewBag.CompraPrecioTotal , mensaje = ""})
<br>
<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Inventario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Almacen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Almacen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioTotal)
            </td>
            <td>
                @Html.ActionLink("Borrar", "Eliminar", new { id = item.Id , id_doc = ViewBag.CompraID, todoElPrecio = ViewBag.CompraPrecioTotal })
            </td>
        </tr>
    }
</table>

<div>
    <dl class="dl-horizontal">
        <dt>
            Precio total de la compra:
        </dt>
        <dd>
            @ViewBag.CompraPrecioTotal
        </dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Finalizar compra", "CompraFinalizada", new { fecha = ViewBag.FechaNoVisible, id = ViewBag.CompraID, idDoc = ViewBag.CompraDocumento, idProv = ViewBag.CompraProveedor, total = ViewBag.CompraPrecioTotal })
</div>

ProyectoEstandares3/ProyectoEstandares3/Views/Compras/Guardar.cshtml
@model ProyectoEstandares3.Models.Compras

@{
    ViewBag.Title = "Registrar compra";
}

<h2>Registrar compra</h2>


@using (Html.BeginForm("NuevaCompra", "Compras", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Id_proveedor, "Id_proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id_proveedor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id_proveedor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fecha, "Fecha", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @Value = @String.Format("{0:yyyy/MM/dd}", DateTime.Now) } })
            @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Siguiente" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEstandares3/ProyectoEstandares3/Views/Compras/Index.cshtml
@model IEnumerable<ProyectoEstandares3.Models.Compras>

@{
    ViewBag.Title = "Lista de Compras";
}

<h2>Lista de Compras</h2>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <font color="green">@ViewBag.confirmacion</font>
    </div>
</div>
<br />
<p>
    @Html.ActionLink("Registrar nueva compra", "Guardar")
</p>
<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Documento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sumas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Iva)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proveedor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Documento)
        </td>
        <td>
            @(String.Format("{0:yyyy/MM/dd}", item.Fecha))
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sumas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Iva)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proveedor)
        </td>
        <td>
            @Html.ActionLink("Detalles", "TodaLaCompra", new { id=item.Id })
        </td>
    </tr>
}

</table>

ProyectoEstandares3/ProyectoEstandares3/Views/Compras/TodaLaCompra.cshtml
@model IEnumerable<ProyectoEstandares3.Models.ComprasDetalle>

@{
    ViewBag.Title = "Detalles de la Compra";
}

<h2>Detalles de la Compra</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Compras.Id)
        </dt>

        <dd>
            @ViewBag.CompraID
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Documento)
        </dt>

        <dd>
            @ViewBag.CompraDocumento
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Proveedor)
        </dt>

        <dd>
            @ViewBag.CompraProveedor
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Fecha)
        </dt>

        <dd>
            @ViewBag.CompraFecha
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Sumas)
        </dt>

        <dd>
            @ViewBag.CompraSumas
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compras.Iva)
        </dt>

        <dd>
            @ViewBag.CompraIva
        </dd>
    </dl>
</div>


<hr>

<h2>Detalles de la compra</h2>

<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Inventario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Almacen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Almacen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioTotal)
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Regresar", "Index", "Compras")
</div>